<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<Platforms>x64</Platforms>
		<TargetFramework>net6.0</TargetFramework>
		<Configurations>Debug;Release;aaaaaaaaa</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="ServiceStack" Version="10.0.6" />
		<PackageReference Include="ServiceStack.Text" Version="10.0.6" />
		<PackageReference Include="Spectre.Console" Version="0.55.2" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="Source\Data\Models\AlternatePassiveAddition.cs">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Compile>
	  <Compile Update="Source\Data\Models\AlternatePassiveSkill.cs">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Compile>
	  <Compile Update="Source\Data\Models\AlternateTreeVersion.cs">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Compile>
	  <Compile Update="Source\Data\Models\PassiveSkill.cs">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Compile>
	  <Compile Update="Source\Data\Models\TreeDataFile.cs">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <None Update="source-data\alternatepassiveadditions.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="source-data\alternatepassiveskills.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="source-data\data.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
	<Target Name="CopyContentFilesToOutputDirectory" AfterTargets="Build;CopyAllFilesToSingleFolderForPackage">
		<ItemGroup>
			<ContentFiles Include="Content\**\*.*" />
		</ItemGroup>
		<Copy SourceFiles="@(ContentFiles)" DestinationFolder="$(OutputPath)%(RecursiveDir)" SkipUnchangedFiles="false" />
		<Copy Condition="'$(PublishProtocol)' == 'FileSystem'" SourceFiles="@(ContentFiles)" DestinationFolder="$(PublishDir)%(RecursiveDir)" SkipUnchangedFiles="false" />
	</Target>
</Project>
